# Generated by Django 5.1.6 on 2025-02-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, verbose_name='Symbol')),
                ('name', models.CharField(max_length=1024, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Rodzaj urządzenia',
                'verbose_name_plural': 'Rodzaje urządzeń',
                'ordering': ['name', 'symbol'],
            },
        ),
    ]
