# Generated by Django 5.1.6 on 2025-03-18 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmms', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.contractor', verbose_name='Firma serwisująca'),
        ),
        migrations.AddField(
            model_name='device',
            name='cost_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.costcentre', verbose_name='Centrum Kosztowe'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.location', verbose_name='Lokalizacja'),
        ),
        migrations.AddField(
            model_name='device',
            name='person_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible', to=settings.AUTH_USER_MODEL, verbose_name='Osoba odpowiedzialna'),
        ),
        migrations.AddField(
            model_name='device',
            name='technical_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Nadzór techniczny'),
        ),
        migrations.AddField(
            model_name='devicegallery',
            name='added_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik dodający'),
        ),
        migrations.AddField(
            model_name='devicegallery',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmms.device', verbose_name='Urządzenie'),
        ),
        migrations.AddField(
            model_name='devicepassport',
            name='added_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik dodający'),
        ),
        migrations.AddField(
            model_name='devicepassport',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmms.device', verbose_name='Urządzenie'),
        ),
        migrations.AddField(
            model_name='document',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.contractor', verbose_name='Kontrahent'),
        ),
        migrations.AddField(
            model_name='document',
            name='device',
            field=models.ManyToManyField(blank=True, to='cmms.device', verbose_name='Urządzenie'),
        ),
        migrations.AddField(
            model_name='document',
            name='person_adding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adding_person', to=settings.AUTH_USER_MODEL, verbose_name='Osoba dodająca dokument'),
        ),
        migrations.AddField(
            model_name='device',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmms.genre', verbose_name='Rodzaj'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='contractor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.contractor', verbose_name='Firma serwisująca'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='cost_centre',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.costcentre', verbose_name='Centrum Kosztowe'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='genre',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cmms.genre', verbose_name='Rodzaj'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.location', verbose_name='Lokalizacja'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='person_responsible',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Osoba odpowiedzialna'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='technical_supervisor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Nadzór techniczny'),
        ),
        migrations.AddField(
            model_name='historicaldevicegallery',
            name='added_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik dodający'),
        ),
        migrations.AddField(
            model_name='historicaldevicegallery',
            name='device',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cmms.device', verbose_name='Urządzenie'),
        ),
        migrations.AddField(
            model_name='historicaldevicegallery',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldevicepassport',
            name='added_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik dodający'),
        ),
        migrations.AddField(
            model_name='historicaldevicepassport',
            name='device',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cmms.device', verbose_name='Urządzenie'),
        ),
        migrations.AddField(
            model_name='historicaldevicepassport',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='contractor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.contractor', verbose_name='Kontrahent'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='person_adding',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Osoba dodająca dokument'),
        ),
        migrations.AddField(
            model_name='historicalgenre',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinspection',
            name='added_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor przeglądu'),
        ),
        migrations.AddField(
            model_name='historicalinspection',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmake',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmileage',
            name='device',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cmms.device', verbose_name='Urządzenie'),
        ),
        migrations.AddField(
            model_name='historicalmileage',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmileage',
            name='person_creating',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utworzony przez'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='contractor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.contractor', verbose_name='Firma serwisująca'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='contractor_execute',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.contractor', verbose_name='Firma wykonująca'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='hospital',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.hospital', verbose_name='Szpital'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='person_assigned',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Osoba przypisana'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='person_completing',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Odbiorca zlecenia'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='person_creating',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Osoba zlecająca'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='person_execute',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Osoba wykonująca'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='contractor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.contractor', verbose_name='Firma serwisująca'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='contractor_execute',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.contractor', verbose_name='Firma wykonująca'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='person_closing',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Osoba zamykająca'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='person_completing',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Odbiorca zlecenia'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='person_creating',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Zgłaszający'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='person_execute',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Osoba wykonująca'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='added_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Autor przeglądu'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='from_which_inspection',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cmms.inspection', verbose_name='Z którego przeglądu'),
        ),
        migrations.AddField(
            model_name='inspectiondevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmms.device', verbose_name='Urządzenie'),
        ),
        migrations.AddField(
            model_name='inspectiondevice',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmms.inspection', verbose_name='Przegląd'),
        ),
        migrations.AddField(
            model_name='inspectiondocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmms.document', verbose_name='Dokument'),
        ),
        migrations.AddField(
            model_name='inspectiondocument',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmms.inspection', verbose_name='Przegląd'),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='added_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Autor zdarzenia przeglądu'),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmms.inspection', verbose_name='Przegląd'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='from_which_inspection_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cmms.inspectionitem', verbose_name='Z którego zdarzenia przeglądu'),
        ),
        migrations.AddField(
            model_name='kit',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmms.device', verbose_name='Urządzenie'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='make',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cmms.make', verbose_name='Producent'),
        ),
        migrations.AddField(
            model_name='device',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmms.make', verbose_name='Producent'),
        ),
        migrations.AddField(
            model_name='mileage',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmms.device', verbose_name='Urządzenie'),
        ),
        migrations.AddField(
            model_name='mileage',
            name='person_creating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utworzony przez'),
        ),
        migrations.AddField(
            model_name='service',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractors_set', to='crm.contractor', verbose_name='Firma serwisująca'),
        ),
        migrations.AddField(
            model_name='service',
            name='contractor_execute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractors_execute_set', to='crm.contractor', verbose_name='Firma wykonująca'),
        ),
        migrations.AddField(
            model_name='service',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.hospital', verbose_name='Szpital'),
        ),
        migrations.AddField(
            model_name='service',
            name='person_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned', to=settings.AUTH_USER_MODEL, verbose_name='Osoba przypisana'),
        ),
        migrations.AddField(
            model_name='service',
            name='person_completing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completing_service', to=settings.AUTH_USER_MODEL, verbose_name='Odbiorca zlecenia'),
        ),
        migrations.AddField(
            model_name='service',
            name='person_creating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creating', to=settings.AUTH_USER_MODEL, verbose_name='Osoba zlecająca'),
        ),
        migrations.AddField(
            model_name='service',
            name='person_execute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persons_execute_service', to=settings.AUTH_USER_MODEL, verbose_name='Osoba wykonująca'),
        ),
        migrations.AddField(
            model_name='document',
            name='service',
            field=models.ManyToManyField(blank=True, to='cmms.service', verbose_name='Zlecenie'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractor_set', to='crm.contractor', verbose_name='Firma serwisująca'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contractor_execute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractor_execute_set', to='crm.contractor', verbose_name='Firma wykonująca'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='device',
            field=models.ManyToManyField(blank=True, to='cmms.device', verbose_name='Urządzenie'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='from_which_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cmms.inspection', verbose_name='Z którego przeglądu'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='from_which_inspection_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cmms.inspectionitem', verbose_name='Z którego zdarzenia przeglądu'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='person_closing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closing', to=settings.AUTH_USER_MODEL, verbose_name='Osoba zamykająca'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='person_completing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completing', to=settings.AUTH_USER_MODEL, verbose_name='Odbiorca zlecenia'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='person_creating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Zgłaszający'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='person_execute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persons_execute', to=settings.AUTH_USER_MODEL, verbose_name='Osoba wykonująca'),
        ),
        migrations.AddField(
            model_name='service',
            name='ticket',
            field=models.ManyToManyField(to='cmms.ticket', verbose_name='Zgłoszenia'),
        ),
        migrations.AddField(
            model_name='document',
            name='ticket',
            field=models.ManyToManyField(blank=True, to='cmms.ticket', verbose_name='Zgłoszenie'),
        ),
        migrations.AddField(
            model_name='mileage',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cmms.unit', verbose_name='Jednostka'),
        ),
        migrations.AddField(
            model_name='historicalmileage',
            name='unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cmms.unit', verbose_name='Jednostka'),
        ),
    ]
