# Generated by Django 5.1.6 on 2025-06-13 09:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='scan',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/tomek/Projects/medbay/protected_site_media'), upload_to='documents/', verbose_name='Plik'),
        ),
    ]
