# Generated by Django 5.1.6 on 2025-06-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0003_alter_document_scan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-id'], 'permissions': (('custom_view_device', 'Może zobaczyć swoje urządzenia'), ('view_all_devices', 'Może zobaczyć wszystkie urządzenia'), ('view_changelist_device', 'Może zobaczyć listę urządzeń (CRM)'), ('view_device_class_chart', 'Może wyświetlać wykres klas urządzeń')), 'verbose_name': 'Urządzenie', 'verbose_name_plural': 'Urządzenia'},
        ),
        migrations.AlterModelOptions(
            name='historicaldevice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Urządzenie', 'verbose_name_plural': 'historical Urządzenia'},
        ),
        migrations.AlterField(
            model_name='devicegallery',
            name='image',
            field=models.ImageField(upload_to='devices/gallery', verbose_name='Zdjecie'),
        ),
        migrations.AlterField(
            model_name='historicaldevicegallery',
            name='image',
            field=models.TextField(max_length=100, verbose_name='Zdjecie'),
        ),
    ]
