# Generated by Django 5.1.6 on 2025-07-23 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0004_alter_device_options_alter_historicaldevice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data rozpoczęcia'),
        ),
    ]
