# Generated by Django 5.1.6 on 2025-07-23 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0005_alter_historicalticket_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='timestamp',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='timestamp',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data rozpoczęcia'),
        ),
    ]
