# Generated by Django 5.1.6 on 2025-02-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
                ('model_name', models.CharField(max_length=4096)),
                ('event_name', models.CharField(max_length=256)),
                ('subject_id', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Wydarzenia',
                'permissions': (('view_event_calendar', 'Może przeglądać kalendarz'),),
                'unique_together': {('subject_id', 'model_name', 'event_name')},
            },
        ),
    ]
