# Generated by Django 5.1.6 on 2025-02-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('street', models.CharField(max_length=255, verbose_name='Ulica')),
                ('street_number', models.CharField(max_length=255, verbose_name='Nr posesji')),
                ('postal_code', models.CharField(max_length=255, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=255, verbose_name='Miejscowość')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo')),
                ('NIP', models.BigIntegerField(verbose_name='NIP')),
                ('REGON', models.BigIntegerField(verbose_name='REGON')),
                ('KRS', models.BigIntegerField(verbose_name='KRS')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon')),
                ('fax', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fax')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Placówka medyczna',
                'verbose_name_plural': 'Placówki medyczne',
            },
        ),
    ]
